### ISSUE TITLE
how to create yaml fixtures for models that include translated fields?

### ISSUE THREAD

**Issue by macolo** [django-parler/django-parler#172]
I would like to create a fixture like this:

```
- model: myapp.location
  pk: null
  fields:
    destination_name: "Location A"

- model: myapp.location
  pk: null
  fields:
    destination_name: "Location B"

- model: myapp.location
  pk: null
  fields:
    destination_name: "Location C"
```
However as `destination_name` is a translated field, the fixture cannot be loaded:

```
fixtures/locations.yaml': Location has no field named 'destination_name'
```

The parler models are dynamic so I don't currently see a solution here. How is this done?
